Controllers/ProduitsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TrackQuality.Areas.Identity.Data;
using TrackQuality.Data;
using TrackQuality.Models;

namespace TrackQuality.Controllers
{
    public class ProduitsController : Controller
    {
        private readonly ApplicationContext _context;

        public ProduitsController(ApplicationContext context)
        {
            _context = context;
        }

        // GET: Liste des produits
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Produit.ToListAsync());
        }

       
        // GET: Produits/Création d'un nouveau produit
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Produits/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("ProduitId,Reference,Prix")] Produit produit)
        {

            //Requête pour vérifier si le produit existe déjà et éviter les doublons dans la BDD
            var produitExist = await _context.Produit.FirstOrDefaultAsync(s => s.Reference == produit.Reference);


            if (ModelState.IsValid)
            {
                if (produitExist == null)
                {
                    try {
                        _context.Add(produit);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    } catch
                    {
                        ModelState.AddModelError(string.Empty, "Une erreur est survenue, merci d'essayer plus tard");
                    }

                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Ce Produit existe déjà");
                }
            }

            return View(produit);


        }

        // GET: Produits/Edit/5
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produit = await _context.Produit.FindAsync(id);
            if (produit == null)
            {
                return NotFound();
            }
            return View(produit);
        }

        // POST: Produits/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("ProduitId,Reference,Prix")] Produit produit)
        {
            if (id != produit.ProduitId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(produit);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProduitExists(produit.ProduitId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(produit);
        }

        // GET: Produits/Delete/5
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produit = await _context.Produit
                .FirstOrDefaultAsync(m => m.ProduitId == id);
            if (produit == null)
            {
                return NotFound();
            }

            return View(produit);
        }

        // POST: Produits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var produit = await _context.Produit.FindAsync(id);
            try
            {
                _context.Produit.Remove(produit);
                await _context.SaveChangesAsync();
               
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Une erreur est survenue, merci d'essayer plus tard");
            }
            return RedirectToAction(nameof(Index));
        }

        private bool ProduitExists(int id)
        {
            return _context.Produit.Any(e => e.ProduitId == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using TrackQuality.Areas.Identity.Data

@inject SignInManager<ApplicationAuthUser> SignInManager
@inject UserManager<ApplicationAuthUser> UserManager


<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>TrackQuality</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback" />
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/lib/adminLTE/plugins/fontawesome-free/css/all.min.css" />
    <!-- Theme style -->
    <link rel="stylesheet" href="~/lib/adminLTE/dist/css/adminlte.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/lib/Datatable/datatables.min.css" />
    <link rel="stylesheet" type="text/css" href="~/lib/Datatable/Responsive-2.2.9/css/responsive.bootstrap4.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <meta name="description" content="application de gestion de non conformite qui inclus une analyse 5M (Ishikawa, Main d'oeuvre, Méthodes, Milieu, Matière, Matériel ) pour trouver la cause racine, une time line pour le suivi d'avancement de l'analyse et action et des indciateurs en temps réels" />
    <link rel="canonical" href="https://trackquality.azurewebsites.net/" />
    <meta property="og:locale" content="fr_FR" />
    <meta property="og:description" content="Gestion des non-conformités produit et indicateurs automatiques intégrés" />
    <meta property="article:author" content="Tatiana Gosso" />

</head>
<body class="sidebar-mini sidebar-collapse layout-fixed" style="height :auto;">
    <div class="wrapper">
        <header>


            <nav class="main-header navbar navbar-expand navbar-white navbar-light">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                    </li>
                    <li class="nav-item d-none d-sm-inline-block">
                        <a asp-controller="Home" asp-action="index" class="nav-link">Accueil</a>
                    </li>

                </ul>

                <!-- Right navbar links -->

                <partial name="_LoginPartial" />

            </nav>

            <aside class="main-sidebar sidebar-dark-primary elevation-4" style="height :100%;">
                <a asp-controller="Home" asp-action="index" class="brand-link">
                    <img src="/img/chart-bar-solid.png" alt="TrackQuality Logo" class="brand-image elevation-2" style="opacity: .8" height="25">
                    <span class="brand-text font-weight-light">TrackQuality</span>
                </a>



                <!-- Sidebar -->
                <div class="sidebar">
                    @if (UserManager.GetUserName(User) != null)
                    {
                        <div class="user-panel mt-3 pb-3 mb-3 d-flex">

                            <div class="image">
                                <img src="/img/user-solid.png" class="elevation-2" alt="User Image" width="10">
                            </div>
                            <div class="info">
                                <a asp-area="Identity" asp-page="/Account/Manage/Index" class="d-block">@UserManager.GetUserName(User)</a>
                            </div>

                        </div>
                    }

                    <!-- Sidebar Menu -->


                    <nav class="mt-2">

                        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                            @if (User.IsInRole("Qualité"))
                            {
                                <li class="nav-item">
                                    <a href="#" class="nav-link">

                                        <i class="nav-icon fas fa-th"></i>
                                        <p>
                                            Non-Conformité
                                        </p>
                                        <i class="right fas fa-angle-left"></i>
                                    </a>
                                    <ul class="nav nav-treeview">
                                        <li class="nav-item">
                                            <a asp-controller="nonConformites" asp-action="Create" class="nav-link">
                                                <i class="far fa-circle nav-icon"></i>
                                                <p>Nouvelle</p>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a asp-controller="nonConformites" asp-action="Index" class="nav-link">
                                                <i class="far fa-circle nav-icon"></i>
                                                <p>Liste</p>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a asp-controller="nonConformites" asp-action="Archive" class="nav-link">
                                                <i class="far fa-circle nav-icon"></i>
                                                <p>Archive</p>
                                            </a>
                                        </li>
                                    </ul>
                                </li>

                            }
                            else if (User.IsInRole("Opérateur"))
                            {
                                <li class="nav-item">
                                    <a href="#" class="nav-link">

                                        <i class="nav-icon fas fa-th"></i>
                                        <p>
                                            Non-Conformité
                                        </p>
                                        <i class="right fas fa-angle-left"></i>
                                    </a>
                                    <ul class="nav nav-treeview">
                                        <li class="nav-item">
                                            <a asp-controller="nonConformites" asp-action="Create" class="nav-link">
                                                <i class="far fa-circle nav-icon"></i>
                                                <p>Nouvelle</p>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a asp-controller="nonConformites" asp-action="IndexUser" class="nav-link">
                                                <i class="far fa-circle nav-icon"></i>
                                                <p>Liste</p>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a asp-controller="nonConformites" asp-action="ArchiveUser" class="nav-link">
                                                <i class="far fa-circle nav-icon"></i>
                                                <p>Archive</p>
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                            }

                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="fas fa-user-cog"></i>
                                        <p>
                                            Admin
                                        </p>
                                        <i class="right fas fa-angle-left"></i>
                                    </a>

                                    <ul class="nav nav-treeview">
                                        <li class="nav-item">
                                            <a asp-controller="Admin" asp-action="ListPers" class="nav-link">
                                                <i class="far fa-circle nav-icon"></i>
                                                <p>Personnel</p>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a asp-controller="Produits" asp-action="Index" class="nav-link">
                                                <i class="far fa-circle nav-icon"></i>
                                                <p>Produit</p>
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                            }
                        </ul>



                    </nav>

                </div>


            </aside>
        </header>

        <section id="section-relative" class="content mb-2" style="height:100%;">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </section>

    </div>



    <script src="~/lib/adminLTE/plugins/jquery/jquery.min.js"></script>
    <script src="~/lib/adminLTE/plugins/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/popper.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/adminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <script type="text/javascript" src="~/lib/Datatable/datatables.min.js"></script>
    <script type="text/javascript" src="~/lib/Datatable/Responsive-2.2.9/js/responsive.bootstrap4.min.js"></script>
    <script src="~/lib/adminLTE/plugins/chart.js/Chart.min.js"></script>
    <script src="~/lib/adminLTE/dist/js/demo.js"></script>

    <script src="~/lib/adminLTE/dist/js/adminlte.min.js"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>