Models/AnalyseNC.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace TrackQuality.Models
{
    public class AnalyseNC
    {
        [Key]
        public int AnalyseId { get; set; }

        [Required(ErrorMessage = "La date est obligatoire.")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Date")]
        public DateTime DateAnalyse { get; set; }

        [Required(ErrorMessage = "Merci de renseigner l'analyse {0}")]
        [DataType(DataType.Text)]
        [Display(Name = "Main d'oeuvre")]
        public string MainDOeuvre { get; set; }

        [Required(ErrorMessage = "Merci de renseigner l'analyse {0}")]
        [DataType(DataType.Text)]
        [Display(Name = "Milieu")]
        public string Milieu { get; set; }

        [Required(ErrorMessage = "Merci de renseigner l'analyse {0}")]
        [DataType(DataType.Text)]
        [Display(Name = "Matière")]
        public string Matiere { get; set; }

        [DataType(DataType.Text)]
        [Display(Name = "Méthode")]
        [Required(ErrorMessage = "Merci de renseigner l'analyse {0}")]
        public string Methode { get; set; }

        [Required(ErrorMessage = "Merci de renseigner l'analyse {0}")]
        [DataType(DataType.Text)]
        [Display(Name = "Matériel")]
        public string Materiel { get; set; }

        //Relation 1 à 1 avec non conformité
        [Required]
        [ForeignKey("NonConformite")]
        public int NonConformiteId { get; set; }
        public NonConformite NonConformite { get; set; }

        //Relation avec Imputation
        [Required]
        [Display(Name = "Imputation")]
        public string ImputationId { get; set; }
        public Imputation Imputation { get; set; }

    }
}

Controllers/NonConformitesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TrackQuality.Areas.Identity.Data;
using TrackQuality.Data;
using TrackQuality.Models;
using TrackQuality.ViewModels;

namespace TrackQuality.Controllers
{
    public class NonConformitesController : Controller
    {
        //Injection de dépendances
        private readonly ApplicationContext _context;
        private readonly UserManager<ApplicationAuthUser> _userManager;
        private readonly IWebHostEnvironment _appEnvironment;
        private readonly RoleManager<IdentityRole> _roleManager;

        //Demande de paramètres dans le constructeur pour pouvoir les utiliser dans les méthodes
        public NonConformitesController(ApplicationContext context, UserManager<ApplicationAuthUser> userManager, IWebHostEnvironment appEnvironment, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _appEnvironment = appEnvironment;
            _roleManager = roleManager;
        }

        //Requêtes en linq
        //Requête pour récupérer toutes les non-conformités en passant par le modèle NonConformite
        private IQueryable<String> ReqFullNcByNc()=> from item in _context.NonConformite select item.NumeroNC;

        //Requête pour récupérer toutes les non-conformités en passant par le modèle NonConformite et trié par EtatAction "En cours"
        private IQueryable<String> ReqFullNcByNcByEnCours() => from item in _context.NonConformite where item.EtatActionId == "En Cours" select item.EtatActionId;

        //Requête pour récupérer toutes les non-conformités en passant par le modèle NonConformite et trié par EtatAction "A Traiter"
        private IQueryable<String> ReqFullNcByNcByATraiter() => from item in _context.NonConformite where item.EtatActionId == "A Traiter" select item.EtatActionId;

        //Requête pour récupérer toutes les non-conformités en passant par le modèle NonConformite et trié par EtatAction "Fermer"
        private IQueryable<String> ReqFullNcByNcByFermer() => from item in _context.NonConformite where item.EtatActionId == "Fermer" select item.EtatActionId;

        //Requête pour récupérer toutes les non-conformités en passant par le modèle NonConformite et trié par EtatAction "En cours" et trié par utilisateur connecté
        private IQueryable<String> ReqFullNcByNcByEnCoursByUser() => from item in _context.NonConformite where item.EtatActionId == "En Cours" where item.ApplicationAuthUserId == _userManager.GetUserId(User) select item.EtatActionId;

        //Requête pour récupérer toutes les non-conformités en passant par le modèle NonConformite et trié par EtatAction "A Traiter" et trié par utilisateur connecté
        private IQueryable<String> ReqFullNcByNcByATraiterByUser() => from item in _context.NonConformite where item.EtatActionId == "A Traiter" where item.ApplicationAuthUserId == _userManager.GetUserId(User) select item.EtatActionId;

        //Requête pour récupérer toutes les non-conformités en passant par le modèle NonConformite et trié par EtatAction "A Traiter" et trié par utilisateur connecté
        private IQueryable<String> ReqFullNcByNcByFermerByUser() => from item in _context.NonConformite where item.EtatActionId == "Fermer" where item.ApplicationAuthUserId == _userManager.GetUserId(User) select item.EtatActionId;

        //Requête pour récupérer toutes les numeroNC en passant par le modèle NonConformite  trié par utilisateur connecté
        private IQueryable<String> ReqFullNumNcByNcByUser() => from item in _context.NonConformite where item.ApplicationAuthUserId == _userManager.GetUserId(User) select item.NumeroNC;

        //Requête pour récupérer tous les états disponible dans le modèle EtatAction
        private IQueryable<String> ReqFullEtatNcByEtatAction() => from item in _context.EtatAction select item.Etat;

        //Requête pour récupérer la photo par NonConformiteId dans le modèle NonConformite
        private IQueryable<String> ReqPhotoByIdByNC(int id) => from item in _context.NonConformite where item.NonConformiteId == id select item.PhotoNC;

        //Requête pour récupérer tous les NumeroNCIncrement dans le modèle NonConformite
        private IQueryable<int> ReqNumIncrementByNC() => from item in _context.NonConformite select item.NumeroNCIncrement;




        //Méthode private qui renvoie un booléen true ou false pour voir si la non-confomité existe déjà en fonction de l'Id
        private bool NonConformiteExists(int id)
        {
            return _context.NonConformite.Any(e => e.NonConformiteId == id);
        }


        //Méthode public récupérant les informations dans le modèle NonConformite et donnant les informations à la vue
        //ViewData pour donner les datas à la vue partielle _IndexSommeNc.cshtml
        // GET: NonConformites
        [HttpGet]
        [Authorize(Roles ="Qualité")]
        public async Task<IActionResult> Index()
        {

            //var trackQualityContext = _context.NonConformite.Include(n => n.ApplicationAuthUser).Include(n => n.EtatAction).Include(n => n.Produit);

            AnalyseActionByNCViewModel model = new AnalyseActionByNCViewModel
            {
                NonConformites = await _context.NonConformite.Include(n => n.ApplicationAuthUser).Include(n => n.EtatAction).Include(n => n.Produit).ToListAsync(),
                AnalyseNCs = await _context.AnalyseNC.Include(n => n.Imputation).ToListAsync(),
                ActionNCs = await _context.ActionNC.Where(p => p.Cloture == false).ToListAsync()
            };

            ViewData["NbNcEnCours"] = ReqFullNcByNcByEnCours().Count();
                ViewData["NbNcATraiter"] = ReqFullNcByNcByATraiter().Count();
                ViewData["NbNcFermer"] = ReqFullNcByNcByFermer().Count();
                ViewData["NbNcTotal"] = ReqFullNcByNc().Count();


            //return View(await trackQualityContext.ToListAsync());
            return View(model);
        }


        //Méthode public récupérant les informations dans le modèle NonConformite et donnant les information à la vue trié par personne connectée
        //ViewData pour donner les datas à la vue partielle _IndexSommeNc.cshtml en fonction des utilisateurs connectés
        //GET: NonConfromites en triant par personne connectée
        [HttpGet]
        [Authorize(Roles = "Opérateur")]
        public async Task<IActionResult> IndexUser()
        {
            //var listNCUser = (from item in _context.NonConformite where item.ApplicationAuthUserId == _userManager.GetUserId(User) select item).Include(n => n.EtatAction).Include(n => n.ApplicationAuthUser).Include(n => n.Produit);

            AnalyseActionByNCViewModel analyseActionByNCViewModel = new AnalyseActionByNCViewModel();
            AnalyseActionByNCViewModel model = analyseActionByNCViewModel;

            model.NonConformites = await _context.NonConformite.Include(n => n.ApplicationAuthUser).Include(n => n.EtatAction).Include(n => n.Produit).Where(p => p.ApplicationAuthUserId == _userManager.GetUserId(User)).ToListAsync();
            model.AnalyseNCs = await _context.AnalyseNC.Include(n => n.Imputation).ToListAsync();
            model.ActionNCs = await _context.ActionNC.Where(p=>p.Cloture == false).ToListAsync();


            ViewData["NbNcEnCours"] = ReqFullNcByNcByEnCoursByUser().Count();
            ViewData["NbNcATraiter"] = ReqFullNcByNcByATraiterByUser().Count();
            ViewData["NbNcFermer"] = ReqFullNcByNcByFermerByUser().Count();
            ViewData["NbNcTotal"] = ReqFullNumNcByNcByUser().Count();
            return View(model);

        }

        //Méthode pour récupérer toutes les NCs clôturées
        [HttpGet]
        [Authorize(Roles = "Qualité")]
        public async Task<IActionResult> Archive()
        {
            AnalyseActionByNCViewModel analyseActionByNCViewModel = new AnalyseActionByNCViewModel();
            AnalyseActionByNCViewModel model = analyseActionByNCViewModel;
            model.NonConformites = await _context.NonConformite.Include(n => n.ApplicationAuthUser).Include(n => n.EtatAction).Include(n => n.Produit).ToListAsync(); ;
            model.AnalyseNCs = await _context.AnalyseNC.Include(n => n.Imputation).ToListAsync();
            model.ActionNCs = await _context.ActionNC.Where(p => p.Cloture ==  true).ToListAsync();

            return View(model);
        }

        //Méthode pour récupérer toutes les NCs clôturées par utilisateur opérateur
        [HttpGet]
        [Authorize(Roles = "Opérateur")]
        public async Task<IActionResult> ArchiveUser()
        {
            var model = new AnalyseActionByNCViewModel
            {
                NonConformites = await _context.NonConformite.Include(n => n.ApplicationAuthUser).Include(n => n.EtatAction).Include(n => n.Produit).Where(p => p.ApplicationAuthUserId == _userManager.GetUserId(User)).ToListAsync(),
                AnalyseNCs = await _context.AnalyseNC.Include(n => n.Imputation).ToListAsync(),
                ActionNCs = await _context.ActionNC.Where(p => p.Cloture == true).ToListAsync()
            };

            return View(model);
        }

        //Méthode afin d'afficher les détails de la non-conformité sélectionnée par l'Id
        // GET: NonConformites/Details/5
        [HttpGet]
        [Authorize(Roles = "Opérateur,Qualité")]
        public async Task<IActionResult> Details(int? id)
        {
            //Gestion de l'erreur si l'id est null
            if (id == null)
            {
                return NotFound();
            }

            //récupération de toutes les informations de la non-confromité en incluant ApplicationAuthUser, EtatAction et Produit par rapport à l'id sélectionné

Views/AnalyseNCs/Create.cshtml
@model TrackQuality.Models.AnalyseNC

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h4 class="text-center my-4">ANALYSE DE LA NON-CONFORMITE </h4>

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-12 col-md-8 ">
        <div class="card card-info">
            <div class="card-header">
                <h4 class="card-title">N° Non Conformite:<span class="ml-4 text-bold"> @ViewBag.NumeroNC</span> </h4>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                </div>
                </div>
                <div class="card-body" style="display:block;">
                    <div class="d-flex flex-column flex-md-row justify-content-between">

                        <div>
                            <table>
                                <tr>
                                    <th scope="row" class="p-2">
                                        Référence:
                                    </th>
                                    <td class="p-2">
                                        @ViewBag.Produit
                                    </td>
                                </tr>
                                <tr>
                                    <th scope="row" class="p-2">
                                        Numéro de série:
                                    </th>
                                    <td class="p-2">
                                        @ViewBag.NumeroSerie
                                    </td>
                                </tr>
                                <tr>
                                    <th scope="row" class="p-2">
                                        Quantité:
                                    </th>
                                    <td class="p-2">
                                        @ViewBag.Quantite
                                    </td>
                                </tr>
                                <tr>
                                    <th scope="row" class="p-2">
                                        Description:
                                    </th>
                                    <td class="p-2">
                                        @ViewBag.DescriptionNC
                                    </td>
                                </tr>
                                <tr>
                                    <th scope="row" class="p-2">
                                        Ouverte par
                                        </th>
                                    <td class="p-2">
                                        @ViewBag.Nom @ViewBag.Prenom
                                        </td>
                                </tr>
                                <tr>

                                    <th scope="row" class="p-2">
                                        Date
                                        </th>
                                    <td class="p-2">
                                        @ViewBag.DateNC

                                        </td>
                                </tr>  
</table>
                        </div>
                        <div>
                            <table>
                                <tr class="text-left">
                                    <th scope="row">
                                        Photo:
                                    </th>
                                    <td>
                                        <img src="~/images/@ViewBag.Photo" width="300" />
                                    </td>
                                </tr>
                            </table>
                        </div>

                    </div>

                </div>

            </div>
    </div>
    <div class="col-md-2"></div>
</div>


<div class="row">
    <div class="col-md-2"></div>
    <div class="col-12 col-md-8">
        <form asp-action="Create" class="card card-info bg-light shadow border-0 mb-4">
            <div class="card-header">
                <h4 class="text-bold text-center">ANALYSE DE LA NON-CONFORMITE</h4>
            </div>
            <div class="card-body p-2 p-md-5">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="MainDOeuvre" class="control-label"></label>
                    <button type="button" class="btn popovers" data-container="body" data-toggle="popover" data-placement="right" data-content="les ressources humaines, les qualifications du personnel...">
                        <i class="fas fa-info-circle"></i>
                    </button>
                    <textarea asp-for="MainDOeuvre" class="form-control" rows="5"></textarea>
                    <span asp-validation-for="MainDOeuvre" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Milieu" class="control-label"></label>
                    <button type="button" class="btn popovers" data-container="body" data-toggle="popover" data-placement="right" data-content="Le lieu de travail, son aspect, son organisation physique…">
                        <i class="fas fa-info-circle"></i>
                    </button>
                    <textarea asp-for="Milieu" class="form-control" rows="5"></textarea>
                    <span asp-validation-for="Milieu" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Matiere" class="control-label"></label>
                    <button type="button" class="btn popovers" data-container="body" data-toggle="popover" data-placement="right" data-content="Les différents consommables utilisés, matières premières…">
                        <i class="fas fa-info-circle"></i>
                    </button>
                    <textarea asp-for="Matiere" class="form-control" rows="5"></textarea>
                    <span asp-validation-for="Matiere" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Methode" class="control-label"></label>
                    <button type="button" class="btn popovers" data-container="body" data-toggle="popover" data-placement="right" data-content="Les procédures, le flux d’information…">
                        <i class="fas fa-info-circle"></i>
                    </button>
                    <textarea asp-for="Methode" class="form-control" rows="5"></textarea>
                    <span asp-validation-for="Methode" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Materiel" class="control-label"></label>
                    <button type="button" class="btn popovers" data-container="body" data-toggle="popover" data-placement="right" data-content="Les équipements, machines, outillages, pièces de rechange…">
                        <i class="fas fa-info-circle"></i>
                    </button>
                    <textarea asp-for="Materiel" class="form-control" rows="5"></textarea>
                    <span asp-validation-for="Materiel" class="text-danger"></span>
                </div>
                <div class="form-group mb-4 text-center">
                    <div class="col-4 m-auto d-block">
                        <label asp-for="ImputationId" class="control-label text-right"></label>
                        <select asp-for="ImputationId" class="form-control" asp-items="ViewBag.ImputationId"></select>
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="VALIDER" class="btn btn-info mx-auto d-block" />
                </div>
            </div>
            <div class="card-footer">
                <div class="card-footer text-center ">
                    <div>
                        @if (User.IsInRole("Qualité"))
                        {
                            <a class="btn btn-info" asp-controller="NonConformites" asp-action="Index">Retour à la liste</a>
                        }
                        else if (User.IsInRole("Opérateur"))
                        {
                            <a class="btn btn-info" asp-controller="NonConformites" asp-action="IndexUser">Retour à la liste</a>
                        }
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-2"></div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/AnalyseNCs/Details.cshtml
@model TrackQuality.Models.AnalyseNC

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row mt-5">
    <div class="col-md-2"></div>
    <div class="col-12 col-md-8 ">
        <div class="card card-info">
            <div class="card-header">
                <h4 class="card-title">N° Non Conformite:<span class="ml-4 text-bold"> @ViewBag.NumeroNC</span> </h4>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                </div>
            </div>

            <div class="card-body" style="display:block;">

                <div class="d-flex flex-column flex-md-row justify-content-between">

                    <div>
                        <table>
                            <tr>
                                <th scope="row" class="p-2">
                                    Référence:
                                </th>
                                <td class="p-2">
                                    @ViewBag.Produit
                                </td>
                            </tr>
                            <tr>
                                <th scope="row" class="p-2">
                                    Numéro de série:
                                </th>
                                <td class="p-2">
                                    @ViewBag.NumeroSerie
                                </td>
                            </tr>
                            <tr>
                                <th scope="row" class="p-2">
                                    Quantité:
                                </th>
                                <td class="p-2">
                                    @ViewBag.Quantite
                                </td>
                            </tr>
                            <tr>
                                <th scope="row" class="p-2">
                                    Description:
                                </th>
                                <td class="p-2">
                                    @ViewBag.DescriptionNC
                                </td>
                            <tr>
                            <tr>
                                <th scope="row" class="p-2">
                                    Ouverte par
                                </th>
                                <td class="p-2">
                                    @ViewBag.Nom @ViewBag.Prenom
                                </td>
                            </tr>
                            <tr>

                                <th scope="row" class="p-2">
                                    Date
                                </th>
                                <td class="p-2">
                                    @ViewBag.DateNC

                                </td>
                            </tr>
                        </table>
                    </div>
                    <div class="">
                        <table>
                            <tr class="text-left">
                                <th scope="row">
                                    Photo:
                                </th>
                                <td>
                                    <img src="~/images/@ViewBag.Photo" width="300" />
                                </td>
                            </tr>
                        </table>
                    </div>

                </div>

            </div>

        </div>
    </div>
    <div class="col-md-2"></div>
</div>

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-12 col-md-8 ">
        <div class="card card-info">
            <div class="card-header">
                <h4 class="card-title">Analyse </h4>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                </div>
            </div>

            <div class="card-body" style="display:block;">
                <div class="d-flex flex-row justify-content-start">

                    <table>

                        <tr>
                            <th scope="row" class="p-2">
                                @Html.DisplayNameFor(model => model.MainDOeuvre)
                            </th>
                            <td class="p-2">
                                @Html.DisplayFor(model => model.MainDOeuvre)
                            </td>
                        </tr>


                        <tr>
                            <th scope="row" class="p-2">
                                @Html.DisplayNameFor(model => model.Milieu)
                            </th>
                            <td class="p-2">
                                @Html.DisplayFor(model => model.Milieu)
                            </td>
                        </tr>


                        <tr>
                            <th scope="row" class="p-2">
                                @Html.DisplayNameFor(model => model.Matiere)
                            </th>
                            <td class="p-2">
                                @Html.DisplayFor(model => model.Matiere)
                            </td>
                        </tr>


                        <tr>
                            <th scope="row" class="p-2">
                                @Html.DisplayNameFor(model => model.Methode)
                            </th>
                            <td class="p-2">
                                @Html.DisplayFor(model => model.Methode)
                            </td>
                        </tr>


                        <tr>
                            <th scope="row" class="p-2">
                                @Html.DisplayNameFor(model => model.Materiel)
                            </th>
                            <td class="p-2">
                                @Html.DisplayFor(model => model.Materiel)
                            </td>
                        </tr>


                        <tr>
                            <th scope="row">
                                @Html.DisplayNameFor(model => model.Imputation)
                            </th>
                            <td class="p-2">
                                @Html.DisplayFor(model => model.Imputation.ImputationNC)
                            </td>
                        </tr>

                    </table>
                </div>
                </div>

                <div class="card-footer text-center ">
                    <div>
                        @if (User.IsInRole("Qualité"))
                        {
                            <a class="btn btn-info" asp-controller="NonConformites" asp-action="Index">Retour à la liste</a>
                        }
                        else if (User.IsInRole("Opérateur"))
                        {
                            <a class="btn btn-info" asp-controller="NonConformites" asp-action="IndexUser">Retour à la liste</a>
                        }
                    </div>
                </div>
            </div>
        </div>
                <div class="col-md-2"></div>
            </div>