Controllers/ActionNCsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TrackQuality.Areas.Identity.Data;
using TrackQuality.Data;
using TrackQuality.Models;
using TrackQuality.ViewModels;

//Classe de gestion des non conformités (create, read, update, delete)
namespace TrackQuality.Controllers
{
    public class ActionNCsController : Controller
    {
        private readonly ApplicationContext _context;
        private readonly UserManager<ApplicationAuthUser> _userManager;
        public ActionNCsController(ApplicationContext context, UserManager<ApplicationAuthUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        private IQueryable<int> ReqNCIdByAnalyseIdFromAnalyseId(int? id) => from item in _context.AnalyseNC where item.AnalyseId == id select item.NonConformiteId;
        private IQueryable<NonConformite> ReqFullNCByNCIdFromNC(int? id) => from item in _context.NonConformite where item.NonConformiteId == id select item;
        private IQueryable<AnalyseNC> ReqFullAnalyseByAnalyseIdFromAnalyse(int? id) => from item in _context.AnalyseNC where item.AnalyseId == id select item;
        private IQueryable<String> ReqFullEtatNcByEtatAction() => from item in _context.EtatAction select item.Etat;
        //Requête pour récupérer les informations de la personne ayant ouvert la NC
        private IQueryable<ApplicationAuthUser> ReqPersCreateNC(string userId) => from item in _userManager.Users where item.Id == userId select item;
        //Méthode de création de paramètre de vue pour les nonconformites et l'analyse en fonction de l'id analyse
        private void NcAndAnalyseViewByIdAnalyse(int? id)
        {
            //récupération de l'id de la non conformité en passant par analyseNC
            var nonconformiteId = ReqNCIdByAnalyseIdFromAnalyseId(id).FirstOrDefault();
            //récupération de toutes les informations de la non conformité concernée
            var nonConformites = ReqFullNCByNCIdFromNC(nonconformiteId).FirstOrDefault();
            //Selection des items voulus de la non conformité pour affichage dans la vue

            ViewData["NumeroNC"] = nonConformites.NumeroNC;
            ViewData["NumeroSerie"] = nonConformites.NumeroSerie;
            ViewData["Quantite"] = nonConformites.QuantiteProdNC;
            ViewData["DescriptionNC"] = nonConformites.DescriptionNC;
            ViewData["Photo"] = nonConformites.PhotoNC;
            ViewData["Nom"] = ReqPersCreateNC(nonConformites.ApplicationAuthUserId).FirstOrDefault().Nom;
            ViewData["Prenom"] = ReqPersCreateNC(nonConformites.ApplicationAuthUserId).FirstOrDefault().Prenom;
            ViewData["DateNC"] = nonConformites.DateNC;

            //Récupération information de l'analyse par l'id analyse récupéré

            var analyse = (from item in _context.AnalyseNC where item.AnalyseId == id select item).FirstOrDefault();
            ViewData["MainDOeuvre"] = analyse.MainDOeuvre;
            ViewData["Methode"] = analyse.Methode;
            ViewData["Matiere"] = analyse.Matiere;
            ViewData["Milieu"] = analyse.Milieu;
            ViewData["Materiel"] = analyse.Materiel;
            ViewData["Imputation"] = analyse.ImputationId;
        }



        // GET: ActionNCs/Details/5
        [HttpGet]
        [Authorize(Roles = "Qualité, Opérateur")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                RedirectToAction("NotFound");
            }



            AnalyseActionByNCViewModel model = new AnalyseActionByNCViewModel
            {
                ActionNC = await _context.ActionNC.Include(a => a.analyseNC).FirstOrDefaultAsync(m => m.ActionId == id)
            };

            if (model.ActionNC == null)
            {
                RedirectToAction("NotFound");
            }

            var idAnalyse = _context.ActionNC.Where(p => p.ActionId == id).Select(p => p.analyseNCId).FirstOrDefault();

            model.AnalyseNC = await _context.AnalyseNC.Where(p => p.AnalyseId == idAnalyse).FirstOrDefaultAsync();

            var idNC = _context.AnalyseNC.Where(p => p.AnalyseId == idAnalyse).Select(p => p.NonConformiteId).FirstOrDefault();

            model.NonConformite = await _context.NonConformite.Include(p=>p.Produit).Include(p => p.ApplicationAuthUser).Where(p => p.NonConformiteId == idNC).FirstOrDefaultAsync();

            return View(model);
        }

        // GET: ActionNCs/Create
        [HttpGet]
        [Authorize(Roles = "Qualité")]
        public IActionResult Create(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            NcAndAnalyseViewByIdAnalyse(id);

            return View();
        }

        // POST: ActionNCs/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Qualité")]
        public async Task<IActionResult> Create(int id, [Bind("ActionId,DescriptionAction,DateAction,analyseNCId,Cloture,Rebuter")] ActionNC actionNC)
        {
            //Récupération des informations sur l'analyse pour récupérer l'id de la nonConformité associée
            var analyse = ReqFullAnalyseByAnalyseIdFromAnalyse(id).FirstOrDefault();
            var nonConformiteId = analyse.NonConformiteId;

            //Récupération du context de la nonConformite pour modifier l'état de la NonConformité
            var nonConformite = await _context.NonConformite.Where(x => x.NonConformiteId == nonConformiteId).SingleOrDefaultAsync();
                        
            //Récupération de la table état pour pouvoir changer l'état de la non conformité
            var etat = ReqFullEtatNcByEtatAction().ToArray();

            //Ajout par défaut de l'id de l'analyse
            actionNC.analyseNCId = id;

            //Ajout par défaut de la date de la validation de l'action
            actionNC.DateAction = DateTime.Now;

            if (ModelState.IsValid)
            {
                //modification de l'état de la NC à solder lors de la validation des actions
                nonConformite.EtatActionId = etat[2];
                try {
                    _context.Update(nonConformite);
                    await _context.SaveChangesAsync();
                } catch
                {
                    ModelState.AddModelError(string.Empty, "Une erreur est survenue, merci d'essayer plus tard");
                }
                try
                {
                    _context.Add(actionNC);
                    await _context.SaveChangesAsync();
                }
                catch
                {
                    ModelState.AddModelError(string.Empty, "Une erreur est survenue, merci d'essayer plus tard");
                }
                

                if(actionNC.Cloture == false)
                {
                    return RedirectToAction("Index", "TimeLine", new { id = nonConformiteId });
                }
                else
                {
                    return RedirectToAction("Index", "NonConformites");
                }
                
                
            }

            /**
             *Préparation de la vue 
             */
            //récupération de l'id de l'analyse
            var analyseId = analyse.AnalyseId;
            NcAndAnalyseViewByIdAnalyse(analyseId);

            return View(actionNC);
        }

        // GET: ActionNCs/Edit/5
        [HttpGet]
        [Authorize(Roles = "Qualité")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                RedirectToAction("NotFound");
            }

            AnalyseActionByNCViewModel model = new AnalyseActionByNCViewModel();
            
            model.ActionNC = await _context.ActionNC.Include(a => a.analyseNC).FirstOrDefaultAsync(m => m.ActionId == id);

            if (model.ActionNC == null)
            {
                RedirectToAction("NotFound");
            }

            var idAnalyse = _context.ActionNC.Where(p => p.ActionId == id).Select(p => p.analyseNCId).FirstOrDefault();

            model.AnalyseNC = await _context.AnalyseNC.Where(p => p.AnalyseId == idAnalyse).FirstOrDefaultAsync();

            var idNC = _context.AnalyseNC.Where(p => p.AnalyseId == idAnalyse).Select(p => p.NonConformiteId).FirstOrDefault();

            model.NonConformite = await _context.NonConformite.Include(p => p.Produit).Include(p => p.ApplicationAuthUser).Where(p => p.NonConformiteId == idNC).FirstOrDefaultAsync();

            return View(model);
        }

        // POST: ActionNCs/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Qualité")]
        public async Task<IActionResult> Edit(int id, AnalyseActionByNCViewModel model)
        {

            if (id != model.ActionNC.ActionId)
            {
                return NotFound();
            }

           
            model.ActionNC.DateAction = DateTime.Now;

            if (model.NonConformite.QuantiteProdNC < model.NonConformite.QtRebute)
            {
                ModelState.AddModelError(string.Empty, "La quantité rebutée ne peut pas être supérieur à la quantité de produit non-conforme.");
            }


            if (ModelState.IsValid)
            {


                try
                {
                    _context.Update(new NonConformite
                    {
                        NonConformiteId = model.NonConformite.NonConformiteId,
                        NumeroNC=model.NonConformite.NumeroNC,
                        DescriptionNC = model.NonConformite.DescriptionNC,
                        DateNC = model.NonConformite.DateNC,

Controllers/TimeLineController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TrackQuality.Data;

namespace TrackQuality.Controllers
{
    public class TimeLineController : Controller
    {
        private readonly ApplicationContext _context;

        public TimeLineController(ApplicationContext context)
        {
            _context = context;
        }
        //Vue sur les étapes du traitement à faire
        // GET: AnalyseNCs
        [HttpGet]
        [Authorize(Roles = "Qualité")]
        public IActionResult Index(int? id)
        {

            var nonConformites = (from item in _context.NonConformite where item.NonConformiteId == id select item).ToArray();
            ViewData["Etat"] = nonConformites[0].EtatActionId;
            ViewData["NonConformiteId"] = nonConformites[0].NonConformiteId;
            ViewData["DateNC"] = nonConformites[0].DateNC;
            ViewData["NumeroNC"] = nonConformites[0].NumeroNC;

            //Récupérationdes informations de l'analyse en cas d'état en cours
            if (nonConformites[0].EtatActionId == "En Cours")
            {
                var analyse = (from item in _context.AnalyseNC where item.NonConformiteId == id select item).ToArray();
                ViewData["DateAnalyse"] = analyse[0].DateAnalyse;
                ViewData["AnalyseId"] = analyse[0].AnalyseId;
                ViewData["NonConformiteId"] = analyse[0].NonConformiteId;

                var nonConformite = (from item in _context.NonConformite where item.NonConformiteId == analyse[0].NonConformiteId select item).ToArray();
                ViewData["DateNC"] = nonConformite[0].DateNC;
                ViewData["NumeroNC"] = nonConformite[0].NumeroNC;
                ViewData["Etat"] = nonConformite[0].EtatActionId;
                ViewData["NonConformiteId"] = nonConformite[0].NonConformiteId;
            }

            if (nonConformites[0].EtatActionId == "Fermer")
            {
                var analyse = (from item in _context.AnalyseNC where item.NonConformiteId == id select item).ToArray();
                ViewData["DateAnalyse"] = analyse[0].DateAnalyse;
                ViewData["AnalyseId"] = analyse[0].AnalyseId;

                var action = (from item in _context.ActionNC where item.analyseNCId == analyse[0].AnalyseId select item).ToArray();
                ViewData["DateAction"] = action[0].DateAction;
                ViewData["ActionId"] = action[0].ActionId;
            }
            return View();
        }
    }
}

Views/TimeLine/Index.cshtml
@model IEnumerable<TrackQuality.Models.AnalyseNC>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">TRAITEMENT DE LA NON-CONFORMITE </h1> <br/>
<h1 class="text-center  mb-5">n° @ViewBag.NumeroNC</h1>


<div class="container col-10 col-md-4 card bg-light shadow border-0 p-4 mx-md-auto mb-4">
    <div class="timeline">
        <!-- timeline time label -->
        <div class="time-label">
            <span class="bg-info">@ViewBag.DateNC</span>
        </div>
        <!-- /.timeline-label -->
        <!-- timeline item -->
        <div>
            <i class="fas fa-check bg-green my-3 text-center"></i>
            <div class="timeline-item p-4 my-3 text-bold bg-green">
                Enregistrement Non-Conformité
            </div>
        </div>
        <!-- END timeline item -->
        @if (@ViewBag.Etat == "A traiter")
        {
            <!-- timeline item -->
            <div>
                <i class="fas fa-play bg-yellow"></i>
                <div class="timeline-item">
                    <h3 class="timeline-header bg-yellow text-center">Analyse 5M</h3>
                    <div class="timeline-body px-4">
                        
                            <a asp-controller="AnalyseNCs" asp-action="Create" asp-route-id="@ViewBag.NonConformiteId">
                                <div class="my-1 btn btn-dark text-white mx-auto d-block">
                                    Créer
                                    <i class="fas fa-edit" style="color:#ffffff; font-size:2em"></i>
                                </div>
                            </a>
                       
                        </div>
                    </div>
            </div>
            <!-- END timeline item -->


            <!-- timeline item -->
            <div>
                <i class="fas fa-exclamation-triangle bg-gray-dark my-3"></i>
                <div class="timeline-item my-3">
                    <h3 class="timeline-header bg-gray text-center">Actions</h3>
                    <div class="timeline-body text-center bg-gray">
                        <i class="fas fa-times-circle" style="color:#252424; font-size:2em"></i>
                    </div>
                </div>
                <!-- END timeline item -->

            </div>
        }
        else if (@ViewBag.Etat == "En Cours")
        {
            <div class="time-label">
                <span class="bg-info">@ViewBag.DateAnalyse</span>
            </div>
            <div>
                <i class="fas fa-check bg-green my-3"></i>
                <div class="timeline-item my-3 text-bold  text-center">
                    <h3 class="timeline-header bg-green">Analyse 5M</h3>
                    <div class="timeline-body px-4">
                        <a asp-controller="AnalyseNCs" asp-action="Edit" asp-route-id="@ViewBag.AnalyseId">
                            <div class="my-1 btn btn-dark text-white">
                                Editer
                                <i class="fas fa-edit" style="color:#ffffff; font-size:2em"></i>

                            </div>
                        </a>
                        <a asp-controller="AnalyseNCs" asp-action="Details" asp-route-id="@ViewBag.AnalyseId">
                            <div class="my-1 btn btn-dark text-white">
                                Voir
                                <i class="fas fa-eye" style="color:#ffffff; font-size:2em"></i>
                            </div>
                        </a>
                    </div>
                </div>
                </div>

            <div>
                <i class="fas fa-play bg-yellow"></i>
                <div class="timeline-item">
                    <h3 class="timeline-header bg-yellow text-center">Action</h3>
                    <div class="timeline-body px-4">
                        <a asp-controller="ActionNCs" asp-action="Create" asp-route-id="@ViewBag.AnalyseId">
                            <div class="my-1 btn btn-dark text-white mx-auto d-block">
                                Créer
                                <i class="fas fa-edit" style="color:#ffffff; font-size:2em"></i>
                                </div>
</a>
                    </div>

                </div>
            </div>

        }
        else
        {

            <div class="time-label">
                <span class="bg-info">@ViewBag.DateAnalyse</span>
            </div>
            <div>
                <i class="fas fa-check bg-green my-3"></i>
                <div class="timeline-item p-4 my-3 text-bold bg-green text-center">
                    <a asp-controller="AnalyseNCs" asp-action="Details" asp-route-id="@ViewBag.AnalyseId">
                        <div class="my-1 btn btn-dark text-white">
                            Voir
                            <i class="fas fa-eye" style="color : #ffffff; font-size:2em"></i>
                        </div>
                    </a>
                </div>
            </div>

            <div class="time-label">
                <span class="bg-info">@ViewBag.DateAction</span>
            </div>
            <div>
                <i class="fas fa-check bg-green my-3"></i>
                <div class="timeline-item p-4 my-3 text-bold bg-green text-center">
                    <a asp-controller="ActionNCs" asp-action="Edit" asp-route-id="@ViewBag.ActionId">
                        <div class="my-1 btn btn-dark text-white">
                            Editer
                            <i class="fas fa-edit" style="color:#ffffff; font-size:2em"></i>

                        </div>
                    </a>
                    <a asp-controller="ActionNCs" asp-action="Details" asp-route-id="@ViewBag.ActionId">
                        <div class="my-1 btn btn-dark text-white">
                            Voir
                            <i class="fas fa-eye" style="color : #ffffff; font-size:2em"></i>
                        </div>
                    </a>
                </div>
            </div>

        }

    </div>
    </div>
<p class="text-center text-md-right mb-5 pr-5">
    <a asp-controller="NonConformites" asp-action="Index" class="btn btn-info">Retour à la liste</a>
</p>